const GAME_CONSTANTS = {
  GAME_HEIGHT: 900,
  GAME_WIDTH: 1600,
};

const PLAYER_CONSTANTS = {
  FROG_SIZE: 80,
  MAX_INJURY: 120,
  RIBBIT_REST: 60 * 5,  // 60 fps * number of seconds
  SPEED: 10,
  TONGUE_TIP_SIZE: 6,
};

const INSECT_CONSTANTS = {
  INSECT_SPEED: 5,
  INSECT_SIZE: 12,
};

module.exports = {
  GAME_CONSTANTS,
  PLAYER_CONSTANTS,
  INSECT_CONSTANTS,
};
